spring.datasource.url=jdbc:postgresql://localhost:5432/ncafedb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=ncafe
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

# 브라우저에서 접근할 URL 패턴
spring.mvc.static-path-pattern=/**
#spring.mvc.static-path-pattern=/images/**
#실제 이미지가 저장된 물리적 경로 (마지막에 / 필수)
spring.web.resources.static-locations=file:./upload/, classpath:/static/

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL Init (Run data.sql always)
spring.sql.init.mode=always