# DB 연결 설정 (환경 변수로 주입)
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# 브라우저에서 접근할 URL 패턴
# spring.mvc.static-path-pattern=/**
#spring.mvc.static-path-pattern=/images/**
#실제 이미지가 저장된 물리적 경로 (마지막에 / 필수)
spring.web.resources.static-locations=${UPLOAD_LOCATION:file:./upload/}, classpath:/static/

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL Init (Run data.sql always)
spring.sql.init.mode=never
# JWT Settings
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Multipart upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-form-post-size=50MB


# Toss Payments
toss.secret-key=${TOSS_SECRET_KEY:}

